In [27]:
import pandas as pd

In [28]:
df = pd.read_csv("train.csv", sep=",")

In [29]:
df.head()

,Number,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,175,She Looks So Perfect,5 Seconds of Summer,boy band,2014,160,95,49,-4,33,44,202,0,13,69
1,577,Run To You,Bryan Adams,album rock,1984,127,81,56,-6,29,64,233,1,3,65
2,275,Stuck On You,Lionel Richie,adult standards,1983,132,32,51,-16,9,25,192,62,3,69
3,514,The Rhythm of the Night,Corona,bubblegum dance,1994,128,81,69,-12,10,80,264,0,3,69
4,300,Beautiful Girls,Sean Kingston,dance pop,2014,118,64,54,-7,24,75,242,14,9,60

In [34]:
df.info

<bound method DataFrame.info of      Number                      title                artist  \
0       175       She Looks So Perfect   5 Seconds of Summer
1       577                 Run To You           Bryan Adams
2       275               Stuck On You         Lionel Richie
3       514    The Rhythm of the Night                Corona
4       300            Beautiful Girls         Sean Kingston
..      ...                        ...                   ...
381     162  Guilty (feat. Barry Gibb)      Barbra Streisand
382     558         Please Mr. Postman       The Marvelettes
383     568  Hypnotize - 2007 Remaster  The Notorious B.I.G.
384     292            The Way We Were      Barbra Streisand
385     126                 In the End           Linkin Park

              top genre  year  bpm  nrgy  dnce  dB  live  val  dur  acous  \
0              boy band  2014  160    95    49  -4    33   44  202      0
1            album rock  1984  127    81    56  -6    29   64  233      1
2       adult standards  1983  132    32    51 -16     9   25  192     62
3       bubblegum dance  1994  128    81    69 -12    10   80  264      0
4             dance pop  2014  118    64    54  -7    24   75  242     14
..                  ...   ...  ...   ...   ...  ..   ...  ...  ...    ...
381     adult standards  1980  151    43    63 -16    11   95  264     23
382  brill building pop  1961  122    78    79  -5    18   97  148     73
383  east coast hip hop  2007   94    69    90  -4    29   63  230     18
384     adult standards  1974  138    32    26 -12    13   17  211     89
385   alternative metal  2000  105    86    56  -6    21   40  217      1

     spch  pop
0      13   69
1       3   65
2       3   69
3       3   69
4       9   60
..    ...  ...
381     4   67
382     3   68
383    28   68
384     3   60
385     6   83

[386 rows x 15 columns]>

In [31]:
media = df.groupby("title")[["dur"]].sum().mean()

In [32]:
media

dur    235.3
dtype: float64

In [38]:
df["cancion_larga"] = df.dur > df.dur.mean()

In [39]:
df.head()

,Number,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop,cancion_larga
0,175,She Looks So Perfect,5 Seconds of Summer,boy band,2014,160,95,49,-4,33,44,202,0,13,69,False
1,577,Run To You,Bryan Adams,album rock,1984,127,81,56,-6,29,64,233,1,3,65,True
2,275,Stuck On You,Lionel Richie,adult standards,1983,132,32,51,-16,9,25,192,62,3,69,False
3,514,The Rhythm of the Night,Corona,bubblegum dance,1994,128,81,69,-12,10,80,264,0,3,69,True
4,300,Beautiful Girls,Sean Kingston,dance pop,2014,118,64,54,-7,24,75,242,14,9,60,True

SQL

SELECT title, IF (dur > AVG(dur), 1, 0) AS VALIDACION FROM df